title: "Controversy"
description: "Blog sur des sujets controversés"
baseurl: "" # pour GitHub Pages, laissez vide
url: "https://taoxadmin.github.io/CONTROVERSY/" # l'URL de votre site

paginate: 5 # Nombre d'articles par page
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

incremental: true

categories:
  - title: "Breaking Controversies"
    path: "/categories/breaking-controversies/"
  - title: "World News & Global Conflicts"
    path: "/categories/world-news-global-conflicts/"
  - title: "Politics & Governance"
    path: "/categories/politics-governance/"
  - title: "Science & Technology"
    path: "/categories/science-technology/"
  - title: "Health & Wellness"
    path: "/categories/health-wellness/"
  - title: "Economy & Finance"
    path: "/categories/economy-finance/"
